env:
  browser: true
  es2021: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:react-hooks/recommended"
  - "plugin:import/recommended"
  - "plugin:import/typescript"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
  - unused-imports
settings:
  react:
    version: "detect"
  "import/parsers":
    "@typescript-eslint/parser": [.ts, .tsx]
  "import/resolver":
    typescript:
      project: assets
rules:
  # The following two rules clash with Prettier
  indent:
    - off
  "@typescript-eslint/no-extra-semi":
    - off
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - never
  unused-imports/no-unused-imports:
    - error
  "@typescript-eslint/no-unused-vars":
    - warn
    - argsIgnorePattern: "^_"
  react/no-unescaped-entities:
    - off
  import/order:
    - off
  sort-imports:
    - off
  # These two rules give false positives because we're using CommonJS
  import/default:
    - off
  import/no-named-as-default-member:
    - off
  prefer-const:
    - error
    - destructuring: all
  "@typescript-eslint/no-non-null-assertion":
    - off
  "@typescript-eslint/ban-ts-comment":
    - off
  # Should we enable this? 🤔
  "@typescript-eslint/no-explicit-any":
    - off
  # TypeScript checks types for us so we don't need this.
  react/prop-types:
    - off
